version: '3.8'

services:
  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - '${WORDPRESS_PORT}:8080'
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=bn_wordpress
      - WORDPRESS_DB_PASSWORD=bitnami
      - WORDPRESS_DB_NAME=bitnami_wordpress
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=admin_password
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - wp-network

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bitnami
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - wp-network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  wp-network:
    driver: bridge
