name: Deploy WordPress on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.SSH_HOST }} 'echo SSH successfully configured'

      - name: Set environment variables
        run: |
          echo "INSTANCE_ID=${{ github.event.number }}" >> $GITHUB_ENV
          echo "SUBDOMAIN=${{ github.event.number }}.lightsail-ip.com" >> $GITHUB_ENV

      - name: Create dynamic docker-compose file
        run: |
          INSTANCE_ID=${{ github.event.number }}
          SUBDOMAIN=${{ github.event.number }}.lightsail-ip.com
          sed "s/wordpress_data:/wordpress_data_${INSTANCE_ID}:/g" docker-compose-template.yml > docker-compose.yml
          sed -i "s/mariadb_data:/mariadb_data_${INSTANCE_ID}:/g" docker-compose.yml
          sed -i "s|http://localhost:8080|http://${SUBDOMAIN}|g" docker-compose.yml
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa docker-compose.yml bitnami@${{ secrets.SSH_HOST }}:/home/bitnami/docker-compose-${INSTANCE_ID}.yml


      - name: Deploy WordPress with Plugin
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.SSH_HOST }} << 'EOF'
            INSTANCE_ID=${{ github.event.number }}
            SUBDOMAIN=${{ github.event.number }}.lightsail-ip.com
            sudo docker-compose -f /home/bitnami/docker-compose-${INSTANCE_ID}.yml down
            sudo SUBDOMAIN=$SUBDOMAIN INSTANCE_ID=$INSTANCE_ID docker-compose -f /home/bitnami/docker-compose-${INSTANCE_ID}.yml up -d
            sleep 30 # wait for the services to start
            sudo docker-compose -f /home/bitnami/docker-compose-${INSTANCE_ID}.yml logs wordpress
            #docker cp /home/bitnami/plugin-directory-${INSTANCE_ID} wordpress:/bitnami/wordpress/wp-content/plugins/
            #docker exec wordpress wp plugin activate plugin-directory --allow-root
          EOF

      - name: Comment on PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SSH_GITHUB_TOKEN }}" \
            -d "{\"body\": \"WordPress instance for this PR is available at http://${{ github.event.number }}.domain.com\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
