name: Deploy WordPress on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@3.112.14.110 'echo SSH successfully configured'

      - name: Set environment variables
        run: |
          echo "INSTANCE_ID=${{ github.event.number }}" >> $GITHUB_ENV
          echo "WORDPRESS_PORT=$((8080 + ${{ github.event.number }}))" >> $GITHUB_ENV

      - name: SSH into Bitnami instance and pull changes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.SSH_HOST }} 'ls'

      - name: List files in the current directory
        run: |
          cd ~
          pwd

      - name: Copy docker-compose file to server
        run: |
          cd ~
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa docker-compose.yml bitnami@${{ secrets.SSH_HOST }}:/home/bitnami/docker-compose-${{ github.event.number }}.yml

      - name: Deploy WordPress with Plugin
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.SSH_HOST }} << 'EOF'
            INSTANCE_ID=${{ github.event.number }}
            WORDPRESS_PORT=$((8080 + $INSTANCE_ID))
            export INSTANCE_ID WORDPRESS_PORT
            docker-compose -f /home/bitnami/docker-compose-${INSTANCE_ID}.yml down
            docker-compose -f /home/bitnami/docker-compose-${INSTANCE_ID}.yml up -d
            sleep 30 # wait for the services to start
            # docker cp /home/bitnami/plugin-directory-${INSTANCE_ID} wordpress:/bitnami/wordpress/wp-content/plugins/
            # docker exec wordpress wp plugin activate plugin-directory --allow-root
          EOF

      - name: Comment on PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.SSH_GITHUB_TOKEN }}" \
            -d "{\"body\": \"WordPress instance for this PR is available at http://${{ github.event.number }}.domain.com\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
