name: Deploy WordPress on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa bitnami@${{ secrets.SSH_HOST }} 'echo SSH successfully configured'

      - name: Deploy WordPress
        run: |
          ssh-keyscan -H 34.235.20.136 >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no bitnami@34.235.20.136 << 'EOF'
            cd ~
            ./scripts/deploy_wordpress.sh ${{ github.event.number }}
          EOF
        shell: /usr/bin/bash -e {0}
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXXBrwoye/agent.1721
          SSH_AGENT_PID: 1722

      - name: Comment on PR
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"WordPress instance for this PR is available at http://${{ github.event.number }}.domain.com\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
